# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go

go:
 - 1.3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools

install:
 - go get code.google.com/p/go.tools/cmd/cover
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/appc/spec/...

script:
 - ./test

